### ISSUE TITLE
The 1.0 Brain

### ISSUE THREAD

**Issue by rafaelcn** [brain-labs/brain#12]
This issue holds all tasks that we need to do to reach **1.0**! If you have done a task, please, mark it, and then add the commit hash aside of the task which you completed it.

# Features and whatnot

- [x] Fix file ```testscripts.c```. 
  - [x] Linux.
  - [x] Mac.
- [x] Implement `?`, `:`, `;`.
- [x] Ignore else's without if's.
- [x] Improve the methods IsBranch, IsTerminator and so on.
- [x] Code refactoring for the return methods inside the recursivity.
- [x] Code refactoring for the whole project. Improve readability (CodeGen params too).
- [x] Create verbose mode describe on https://github.com/luizperes/brain/issues/2
- [x] Fix InputExpression
- [x] Implement optimization for empty whiles `[ ]`. Ignore them (For Else too).
- [x] Implement optimization for empty moves `ShiftExpr(0)` and `IncrementExpression(0)`.
- [x] Change the if and while.`if (*ptr != 0)`, not `if (*ptr > 0)`. Although for is going to work only for positive numbers.
- [x] Implement `-version` flag.
- [x] Allow the compiler to have cells larger than 100 x 4
- [x] Implement a `generate optimized code` option for the compiler.
- [x] Implement a `delete comments` option for the compiler.
- [x] Improve the `return` at the method `Parser::isSkippable`. Check switch at the parser.
- [x] Change module's name.
- [x] Code's refactoring:
  - [x] Move the content of brain.cpp to a boostrap file.
  - [x] Refactor parser.cpp.
- [x] Make sure you are deleting objects from the heap.
- [x] Implement `$` as a print for number / 100. 
  - [x] Create tests for `$` as well.
- [x] Check if required functions (LLVM IR) are implemented.
- [x] Breaks are not working inside if (they are going back to the beginning of the loop)
- [x] Fix verbose mode and levels for the debug mode
- [x] Create install script. (remember to install the libs)

# Documentation

- [x] Utils #24 
- [x] Parser #24
- [x] Expressions #24
- [x] AST #24

**Comment by rafaelcn** [comment]
Maybe the _Allow the compiler to have cells larger than 100x4_ was solved as in the _[parser.h](https://github.com/luizperes/brain/blob/master/src/parser/Parser.h#L26-L27)_ a variable k_cells_count is implemented, am I correct @luizperes?

**Comment by luizperes** [comment]
@rafaelcn That is partially correct, once we still need to take that value from the command line args

**Comment by rafaelcn** [comment]
So on what solution are you thinking about? Passing it through **brain** command line?

**Comment by luizperes** [comment]
@rafaelcn I think so... I didn't want to create `two` more commands for adding/reducing the tape size... I think that we should leave the tape size fixed, although with a possibility of setting it up

**Comment by rafaelcn** [comment]
A config file would be nice, however, it would increase the complexity of the project right now. Although, accepting custom settings from a file would be awesome :+1:

**Comment by luizperes** [comment]
I completely agree with you, could you create this suggestion as an issue? We can try to release that after that version 1.0

**Comment by rafaelcn** [comment]
Ok!

**Comment by luizperes** [comment]
Is the documentation done @rafaelcn ? 
Could you check the items that are done? :)

**Comment by rafaelcn** [comment]
Yes, just waiting to check them out when I submit everything

**Comment by ryukinix** [comment]
Checking this delicious issue and the giant amount of subtasks. Go a head, @rafaelcn!

**Comment by rafaelcn** [comment]
We just need to package everything now. :package:

**Comment by ryukinix** [comment]
We need put this on AUR 
@Kurichiel

**Comment by luizperes** [comment]
The Dockerfile was just done and updated a new version! :) We did it at 11:57

**Comment by ryukinix** [comment]
FINALLY!
