### ISSUE TITLE
Create a config file for brain

### ISSUE THREAD

**Issue by rafaelcn** [brain-labs/brain#15]
A tool that accepts its configuration with a file is highly customizable and fairly easy to work, we save two things when implementing a configuration file:
- Time
- Time

The process of compilation can last longer as the project increases, so it's to keep those things in mind. Therefore a configuration file to _Brain_ would be nice to be implemented. All the properties of _Brain_ would be customizable from that file.

**Comment by luizperes** [comment]
in order to finish the milestone 1.1 fast, I am taking it off

**Comment by rafaelcn** [comment]
Are we wiling to create this @luizperes?

**Comment by luizperes** [comment]
Hi @rafaelcn, as mentioned before to you, I think that the makefile will make the same or a better job, not mentioning that many people are used to it. Take a look to an example here: https://github.com/brain-labs/brain/blob/master/repl/Makefile . What do you think ?

**Comment by rafaelcn** [comment]
Yes, I was just trying to address this issue before closing it. I also think that the Makefile is sufficient for now.
