### ISSUE TITLE
Transfering the repository to `brain-labs`

### ISSUE THREAD

**Issue by ryukinix** [brain-labs/brain#22]
I setup right now all the basic necessary structure and invoked you, @luizperes , as the Team Maintainer. As you wish, you can add more people and create new teams, as new repository too.

The structure is:

```common-lisp

(setf brain-labs ('brain
                  'brain-repl
                  'brain-docs
                  'brain-experiments
                  'brain-examples
                  'brain-training
                  'brain-labs.github.io))
```

You are welcome.

**Comment by rafaelcn** [comment]
`lisp` notation, approved. :+1:

**Comment by luizperes** [comment]
Done! :dancer:
