### ISSUE TITLE
Implementation of the symbol `^`

### ISSUE THREAD

**Issue by luizperes** [brain-labs/brain#23]
Implement new command `^` 

Benefits:
Right now, If you want to move from the _1st cell_ to _100th cell_ you will need to write something like:

1st way

``` Brainfuck
++++++++++>**-{>}
```

2nd way

``` Brainfuck
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

While the `1st way` runs in `O(n)`, the `2nd way` runs in `O(1)`, where `n` is the desired cell. In this way, the 2nd way of writing is way faster, however, when the desired cell increases/decreases (let's think in a big number like `1000000`), we would need need to write the command `>` one million times!

That is why I think that we should have a command `^`.
In this way, if one wanted to move the pointer from the `1st cell` to the `1-million-th cell` that would be as easy as:

``` Brainfuck
++++++++++>+******^
```

That would be also `O(1)` for all cases :D

**Comment by rafaelcn** [comment]
We've been discussing this and this could improve Brain by saving us - and the _AI_ in the future - time to write code and also to interpret code as that would make O(1) code no matter what.

**Comment by luizperes** [comment]
New feature implemented [here](https://github.com/brain-labs/brain/commit/ca2b1cbff442b4efac9fb737815396a29c08018c). Please check it out @rafaelcn and @ryukinix

**Comment by rafaelcn** [comment]
Beautiful! If it is working you can close it. Not having much time to test things around, green flag for you. :-)

**Comment by luizperes** [comment]
Closed on the https://github.com/brain-labs/brain/commit/ca2b1cbff442b4efac9fb737815396a29c08018c
