### ISSUE TITLE
Binary generation

### ISSUE THREAD

**Issue by rafaelcn** [brain-labs/brain#25]
The compiler should also, besides being a JIT compiler, read a _brain_ file and generate an executable, the discussion is concerned on to whether the compiler should generate it only when requested, throught  a flag, or it would generate the binary when called, like _gcc_ and other compilers do.

**Comment by luizperes** [comment]
I will add this issue to the `milestone 1.0`

**Comment by rafaelcn** [comment]
Really? Shouldn't we put another milestone to implement our new ideas and close the 1.0 ASAP? The dead line is tight!

**Comment by luizperes** [comment]
@rafaelcn OK! You've got a strong point there! Thanks for this issue, though! :)

**Comment by ryukinix** [comment]
Nice issue

**Comment by rafaelcn** [comment]
So as you all are here you should help to decide which one of the behavior we should implement:

1. Generate a binary file only when asked? Solution using a flag, something like `--out=<bin_name>`
2. Generate a binary file when called the compiler over a file.

**Comment by ryukinix** [comment]
I vote to do like others interpreters. Like lisp and python. `-c` flag denotes compile to machine language and save the file for standard like `source-name.bc`

**Comment by ryukinix** [comment]
considering the usage of extension `b` as the natural extension for brain

**Comment by luizperes** [comment]
I agree with @ryukinix regarding using flags! :)

But only making a point here, __Brain__ extensions are `.b`, `.br` and `.brain` and I think that we should include `.bf`, as _Brainfuck_ itself uses `.b` and `.bf`.

**Comment by luizperes** [comment]
I will also add `.wit`

**Comment by rafaelcn** [comment]
Why `.wit`?

**Comment by luizperes** [comment]
`Wit` is a form of intelligent humour, what is close to what `Brain` is. It is also `3 chars` long, as mentioned and proposed by @leonardo neumann

**Comment by luizperes** [comment]
Included `.bf` and `.wit` on https://github.com/brain-labs/brain/commit/fa350046475298f0a2528bc38cb03a5f43668951

**Comment by luizperes** [comment]
We are generating the `*.o` file at the https://github.com/brain-labs/brain/commit/70fbef26bc237a484d4635a2d3c961dbbd627be2 . I believe that I will leave like that, once `clang` itself uses __`ld`__ - [Explanation here](http://stackoverflow.com/questions/11657529/how-to-generate-an-executable-from-an-llvmmodule) and other people use __`gcc`__ - [Explanation here](http://stackoverflow.com/questions/14558977/ld-start-not-found-defaulting-to). There is still other ways of doing that, but all of them use external tools and I don't like it. For that, I think that I will leave up to the user to use a __`Makefile`__ and this would also solve https://github.com/brain-labs/brain/issues/15. What do you guys think?

**Comment by luizperes** [comment]
Brain now has 3 new flags to solve this issue:

- `c` Generates object code
- `S` Generates assembly code
- `out=<filename>` Sets the output filename `// only works together with -c or -S`

We will not generate binary directly because of the problem that I mentioned above. Checkout the commit https://github.com/brain-labs/brain/commit/b3ebaeda2babefa377c9bc3e249070dc85ec4bb3
