### ISSUE TITLE
Makefile rules build and install are mixed and confused

### ISSUE THREAD

**Issue by ryukinix** [brain-labs/brain#29]
This is very annoying. The build triggers are getting sudo permissions to modify the OS filesystem on building the brain compiler. 

I think it is better move all the statements for linking/creating libraries, move binaries and other stuffs to `install` trigger and keep `build` rule to just... build. 

This is really more simple and clear.

So the INSTALL process will be:

``` bash
make
sudo make install
```

I'm really angry about that, because I'm pain with the idiomatic way to build packages on ArchLinux don't allow to modify the OS before build the package. All the files need be put a sandbox, so after compressed, the system get all the files whose will be inserted on operating system and that way we can know exactly the files installed after it. That way is very simple remove the package.

Yes, it's very bad.

![photo_2016-10-01_22-44-59](https://cloud.githubusercontent.com/assets/7642878/19018027/cab110a8-8828-11e6-90e1-b688d0b5564f.jpg)

**Comment by luizperes** [comment]
Thanks for you comment @ryukinix, I actually felt the same way! I will change it for sure. At first I was trying to include the Brain compiler with the LLVM folder for front end, but I think that I will switch it with the local path. What do you think?

**Comment by luizperes** [comment]
@rafaelcn

**Comment by rafaelcn** [comment]
I agree, but what do you mean by local path @luizperes? `usr/local/`?

**Comment by luizperes** [comment]
Actually, @rafaelcn, I was thinking about something else. What do you think about `~/.local/`?

**Comment by rafaelcn** [comment]
Great, looks good. I'd place it on: `~/.local/lib/brain/io.ll`.

**Comment by ryukinix** [comment]
You can make this in next release? By the way, would be really if a full changelog  been wrote in the next release and so on.

thanks. i'm wating for that fix to reduce the pain of my Obsessive Compulsive Disorder.

**Comment by luizperes** [comment]
I will certainly do it @ryukinix!! No problem! I have the same problem (that was actually bothering me for a long time too)

**Comment by luizperes** [comment]
taking off milestone 1.1

**Comment by ryukinix** [comment]
@luizperes credo

**Comment by luizperes** [comment]
I might put it back, @ryukinix :P

**Comment by luizperes** [comment]
I believe I fixed it [here](https://github.com/brain-labs/brain/commit/3f220cd94880430b0a8b138a7877ac289a34b18b) @ryukinix . Could you check it please?

**Comment by rafaelcn** [comment]
What do you think of placing it inside `./local/lib/...` instead of the plain home folder @luizperes?

**Comment by luizperes** [comment]
isn't it on `~/local/lib`?... or you want to put it there for a reason? `//(omit the libraries)? `

**Comment by rafaelcn** [comment]
Ops, my bad. Edited the comment, can you please take a second look?

**Comment by luizperes** [comment]
As talked to you on chat, I will leave it on: `$HOME/.brain/lib`, ok?

**Comment by luizperes** [comment]
That was done [here](https://github.com/brain-labs/brain/commit/f4e60421d8409ee75abc5ba45c76b906a7201d89)

**Comment by ryukinix** [comment]
> keep build just... to build.

**Comment by luizperes** [comment]
Hi @ryukinix ! Thanks for the hint! I'm reopening this issue!

**Comment by luizperes** [comment]
Done

**Comment by luizperes** [comment]
This shit is not good enough xD

**Comment by ryukinix** [comment]
[libs/install.sh](https://github.com/brain-labs/brain/blob/b7f5380e699964d457c89a59bfa6053347f4d34c/libs/install.sh#L30) this file is evil.

Please, build the binary without the need to modify the operating system, injecting files or whatever be.

**Comment by ryukinix** [comment]
Questions on makefile build no... :( there is no way to build without modifying the system? Build is just to build, for modify we already have the install rule....

**Comment by ryukinix** [comment]
> Well, should it ask for the user if he wants to install in a pre defined folder <folder> or just build the lib and brain in bin?

I think anything about that should be only related to `make install`. And I think that making questions on makefile is not a good idea. Brakes automation. You can just do that by specifying params, overide variables of make. `make PREFIX=/usr install` and so on...

**Comment by rafaelcn** [comment]
Well, you got the point. I wasn't referring to it in the `make build`, I was talking about `make install`. But you got a point, we can change the prefix to change installation binaries, this issue will be put on hold as me and @luizperes are talking about merge the io/math library in Brain itself.

**Comment by luizperes** [comment]
initial external scripts should die! :D 

(if the user wants to extend Brain using external libraries will be still possible, but all the dependencies to `clang` (_not clang_++_) should be removed!

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
