### ISSUE TITLE
Create .deb package and a ubuntu ppa channel for Brain

### ISSUE THREAD

**Issue by ryukinix** [brain-labs/brain#31]
Well, as I already wrote a package for Arch Linux using PKGBUILD, the good news is I found a transpiler package: https://github.com/matthewbauer/unipkg

Take a look, we can generate the .deb packages with a formal ArchLinux package. After #29 fixed I can do this.

**Comment by luizperes** [comment]
Wow!!! That sounds awesome @ryukinix !!!! Can you update us regarding this issue?

Thank you!

**Comment by texrg** [comment]
Why not normal debian or fedora package?

**Comment by rafaelcn** [comment]
If you would like one @texrg you can create and maintain it, I think that we just don't have the time to support the package now.

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
