### ISSUE TITLE
BreakExpr for nested stmts

### ISSUE THREAD

**Issue by luizperes** [brain-labs/brain#41]
BreakExpr does not seem to be working properly for nested statements, such as an IfExpr in a LoopExpr

**Comment by rafaelcn** [comment]
How it isn't working properly? It is breaking every nested statement from within or it doesn't break any IfExpr or LoopExpr at all?

**Comment by luizperes** [comment]
It does not break in statements such as:

```
   LoopExpr
     IfExp
       BreakExp
```

It happens because the `code_gen` is not finding the nearest loop. I have got to check it, though

**Comment by luizperes** [comment]
I have done the proper tests [here](https://github.com/brain-labs/brain/commit/78c4a813d5e3092560ad3da3050ae71a58f27b71) and it seems to be working. I will for Travis and will close this issue right after.
