### ISSUE TITLE
Makefile and bash scripts problems

### ISSUE THREAD

**Issue by luizperes** [brain-labs/brain#46]
Our current problems are:
- `aliases` on Linux seem to not be working with clang on Brain.
- Brain can be compiled with the versions of LLVM 3.5, 3.8 and 3.9 (we have not tested versions 3.6 and 3.7)
- We have way too many `bash` scripts. Should we reduce it?

**Comment by luizperes** [comment]
It seems that this problem is related to the `llvm-config`, @rafaelcn

**Comment by rafaelcn** [comment]
It also is! You have to specify the version of `clang` and also of `llvm-config`. What I did to minimize the errors was to create a symbolic link to both.

**Comment by luizperes** [comment]
Solved on #49
