### ISSUE TITLE
Uninitialized flag

### ISSUE THREAD

**Issue by luizperes** [brain-labs/brain#51]
Clang is complaining that we did not initialize a variable
![uninitialized](https://user-images.githubusercontent.com/6173065/31596195-c0d4b33a-b1f5-11e7-87d9-c15d96788a83.png)

**Comment by rafaelcn** [comment]
I'll take a look at this later!

**Comment by luizperes** [comment]
Thanks!

**Comment by rafaelcn** [comment]
Would you please tell which build did you use in Makefile @luizperes, here it doesn't trigger any warning on `make` or `make build-3.9`.

**Comment by luizperes** [comment]
Interesting, it happened with me on ‘make build-3.8’. I will take this one them, thanks! :)

**Comment by rafaelcn** [comment]
Interesting , a bug maybe? That sounds reasonable as `rm` is not initialized in ljne 127, but so is `opt` in line 126 and that doesn't trigger any other warning, does it?

**Comment by luizperes** [comment]
I will be take some time later for that and will update you

**Comment by luizperes** [comment]
This warning is not happening on newer versions, so I will just let it the way it is. :)

**Comment by rafaelcn** [comment]
Yep, this shouldn't happen in newer versions of llvm as it is a bug.
