### ISSUE TITLE
Rename expression files (and classes)

### ISSUE THREAD

**Issue by luizperes** [brain-labs/brain#60]
We need to rename all files and classes because they are being described wrongly.
For example:

`OutputExpr`, should be `OutputStmt`, however, `ArithmeticExpr` should probably be kept the same. We need to discuss it.

Any thoughts @haskellcamargo, @ryukinix, @rafaelcn ?

**Comment by ryukinix** [comment]
Hmm... this is bad, but easy to fix with a good editor. Statement means a instruction, expression however means a instruction and is signed to a value to be returned, is it? I mean.... I'm trying to figure out what is the problem. If is this and you want to change the name to describe all the operations correctly, you should list what class was described wrongly on this issue.

But how about using a more generic name? Like `Operation` or something else. That way would be `OutputExpr` -> `OutputOp`. But I'm not sure about that.

**Comment by haskellcamargo** [comment]
We first need to list everything that should be renamed and why. The concepts of `Statement` and `Expression` differ from language to language and some languages have only one kind of node. In Quack, now, we have statements, expressions and also *declarations*. In Brain, actually, if nothing really returns and the things can be remapped to *opcodes*, I believe we have *instructions* (statements are, in general, a lot more complex), like Assembly. In Haskell, for example, we only have expressions and declarations (statements don't exist!). For Brain, the fact is: `OutputExpr` is not an `Expr`, but an instruction.

**Comment by ryukinix** [comment]
I agree with `Instrunction` as replacement for the suffix` Expression`, the only problem is that I did not find a good and short way to write `Instruction` as I can find for`Expression` or` Statement`. I mean ... `OutputExp` seems clearly what is, but` OutputInstr` is good? Keeping in the long form `OutputInstrunction` is to me too long if this matters - but this is only aesthetics, anyway.

**Comment by luizperes** [comment]
Instr sounds cool to me, such as llvm do

**Comment by ryukinix** [comment]
If is a common jargon on LLVM, I'm ok with it.
