### ISSUE TITLE
guys, are you still alive? the last commit happened in 2020

### ISSUE THREAD

**Issue by mb6ockatf** [brain-labs/brain#72]

**Comment by rafaelcn** [comment]
We still are but things are happening in our lives that prevent us from moving this project further

**Comment by rafaelcn** [comment]
I was porting this project to LLVM 15 but I stopped after a few weeks, I have work and a university behind my back but I think @luizperes might be more free now that he finished his masters degree 😆

**Comment by mb6ockatf** [comment]
@rafaelcn so you started this project when in university?

**Comment by mb6ockatf** [comment]
@rafaelcn thanks for answer btw

**Comment by rafaelcn** [comment]
> @rafaelcn so you started this project when in university?

A tad bit before I got into the university.

**Comment by luizperes** [comment]
I have time for things now @rafaelcn @mb6ockatf, so feel free to add any questions/submit any bugs you find/submit any PRs you may be interested. Thanks for showing interest. 😄
